# Generated by Django 5.1.2 on 2024-11-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('MA', 'Masculino'), ('F', 'Femenino'), ('X', 'No Binario')], max_length=20),
        ),
    ]
